apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: obc-observability
  namespace: openshift-storage
  labels:
    app.kubernetes.io/name: observability
    app.kubernetes.io/component: storage
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  generateBucketName: obc-observability-bucket
  storageClassName: openshift-storage.noobaa.io
---
#apiVersion: operator.openshift.io/v1
#kind: Console
#metadata:
#  name: cluster
#spec:
#  plugins:
#  - odf-console
