apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  labels:
    open-cluster-management.io/policy-set: openshift-plus
  name: binding-openshift-plus-managed
  namespace: open-cluster-management
  annotations:
    argocd.argoproj.io/sync-wave: "2"
placementRef:
  name: placement-openshift-plus-managed
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-ocm-observability
  kind: Policy
  apiGroup: policy.open-cluster-management.io
