#!/usr/bin/env ansible-playbook
---
- name: Install a metal worker
  become: false
  connection: local
  hosts: localhost
  gather_facts: false
  vars:
    kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
    machineset_instance_type: m5.metal
    machineset_machine_role: worker
    machineset_machine_type: worker
    machineset_name: metal-worker
    machineset_node_labels:
      node-role.kubernetes.io/worker: ""
    machineset_replicas: 1
    machineset_user_data_secret: worker-user-data
    machineset_user_data_namespace: openshift-machine-api
    max_machineset_count: 2
  tasks:
    - name: Query Cluster Infrastructure Name
      kubernetes.core.k8s_info:
        api_version: config.openshift.io/v1
        kind: Infrastructure
        name: cluster
      register: cluster_info

    - name: End play if not AWS
      ansible.builtin.meta: end_play
      when:
        - cluster_info.resources[0].status.platform not in [ "AWS" ]

    - name: Set Dynamic MachineSet Facts
      ansible.builtin.set_fact:
        infrastructure_name: "{{ cluster_info.resources[0].status.infrastructureName }}"
        infrastructure_region: "{{ cluster_info.resources[0].status.platformStatus.aws.region }}"

    - name: Query MachineSets
      kubernetes.core.k8s_info:
        api_version: machine.openshift.io/v1beta1
        kind: MachineSet
        namespace: openshift-machine-api
      register: cluster_machinesets_raw

    - name: Extract worker machinesets
      ansible.builtin.set_fact:
        cluster_machinesets: "{{ cluster_machinesets_raw.resources | selectattr('metadata.name', 'match', '-worker-') }}"

    - name: Extract target machinesets
      ansible.builtin.set_fact:
        target_machineset_resources: "{{ cluster_machinesets.resources[0:max_machineset_count | int] }}"

    - name: Ensure we have at least two machines if only one machineset
      ansible.builtin.set_fact:
        machineset_replicas: 2
      when: target_machineset_resources | length == 1

    - name: Define template for creating machineset
      ansible.builtin.set_fact:
        machineset_yaml: |
          ---
          {% for res in target_machineset_resources %}
          - apiVersion: machine.openshift.io/v1beta1
            kind: MachineSet
            metadata:
              labels:
                machine.openshift.io/cluster-api-cluster: "{{ infrastructure_name }}"
                edge-gitops-role: kubevirt-worker
              name: "{{ infrastructure_name }}-{{ machineset_name }}-{{ res.spec.template.spec.providerSpec.value.placement.availabilityZone }}"
              namespace: openshift-machine-api
            spec:
              replicas: {{ machineset_replicas | int }}
              selector:
                matchLabels:
                  machine.openshift.io/cluster-api-cluster: "{{ infrastructure_name }}"
                  machine.openshift.io/cluster-api-machineset: "{{ infrastructure_name }}-{{ machineset_name }}-{{ res.spec.template.spec.providerSpec.value.placement.availabilityZone }}"
              template:
                metadata:
                  labels:
                    machine.openshift.io/cluster-api-cluster: "{{ infrastructure_name }}"
                    machine.openshift.io/cluster-api-machine-role: "{{ machineset_machine_role }}"
                    machine.openshift.io/cluster-api-machine-type: "{{ machineset_machine_type }}"
                    machine.openshift.io/cluster-api-machineset: "{{ infrastructure_name }}-{{ machineset_name }}-{{ res.spec.template.spec.providerSpec.value.placement.availabilityZone }}"
                spec:
                  metadata:
                    labels: {{ machineset_node_labels }}
                  providerSpec:
                    value:
                      ami:
                        id: "{{ res.spec.template.spec.providerSpec.value.ami.id }}"
                      apiVersion: awsproviderconfig.openshift.io/v1beta1
                      blockDevices: {{ res.spec.template.spec.providerSpec.value.blockDevices }}
                      credentialsSecret:
                        name: aws-cloud-credentials
                      deviceIndex: 0
                      iamInstanceProfile:
                        id: "{{ infrastructure_name }}-worker-profile"
                      instanceType: "{{ machineset_instance_type }}"
                      kind: AWSMachineProviderConfig
                      placement:
                        availabilityZone: "{{ res.spec.template.spec.providerSpec.value.placement.availabilityZone }}"
                        region: "{{ infrastructure_region }}"
                      securityGroups: {{ res.spec.template.spec.providerSpec.value.securityGroups }}
                      subnet:
                        filters:
                          - name: tag:Name
                            values:
                              - "{{ res.spec.template.spec.providerSpec.value.subnet.filters[0]['values'][0] }}"
                      tags: {{ res.spec.template.spec.providerSpec.value.tags }}
                      userDataSecret:
                        name: "{{ machineset_user_data_secret }}"
                        namespace: "{{ machineset_user_data_namespace }}"
          {% endfor %}

    - name: Get definitions
      ansible.builtin.set_fact:
        machineset_definitions: "{{ machineset_yaml | from_yaml }}"

    - name: Create MachineSet
      kubernetes.core.k8s:
        definition: "{{ item }}"
        state: present
      loop: "{{ machineset_definitions }}"
